server:
  port: 8081

spring:
  application:
    name: "auth-service"
  datasource:
    url: jdbc:postgresql://auth-postgresdb:5432/videostreaming_service_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  security:
    secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
    token-life-minutes: 60

springdoc:
  swagger-ui:
    path: /swagger-ui

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
