server:
  port: 8083

spring:
  application:
    name: "video-storage-service"
  kafka:
    topic: updated-download-link
    bootstrap-servers: kafka-broker:19092

topic:
  partitions: 3
  replicas: 1
  
yandex-api:
  oauth-token: y0_AgAAAABGVMkQAADLWwAAAAD0e36wiL8v8-SISMeCCEKFSq83IeJyy6c

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
